FROM node:22

# Install compilers and runtimes
RUN apt-get update && apt-get install -y \
    g++ \
    gcc \
    default-jdk \
    python3 \
    && rm -rf /var/lib/apt/lists/*

# Create non-root user
RUN useradd -m judge

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Create sandbox directory
RUN mkdir -p /app/sandbox && \
    chown -R judge:judge /app/sandbox

# Run application as non-root
USER judge

EXPOSE 5000

CMD ["npm", "start"]